<#
.SYNOPSIS
    Set up architecture design environment and copy templates.
.DESCRIPTION
    Creates docs/ and docs/adr/ directories, copies architecture template,
    finds feature specifications, and outputs paths as JSON.
.EXAMPLE
    .\scripts\setup-architect.ps1
.NOTES
    Platforms: Windows PowerShell 5.1+, PowerShell 7+ (cross-platform)
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SkillDir = Split-Path -Parent $ScriptDir
$TemplatesDir = Join-Path $SkillDir 'templates'

# Find repository root
function Find-RepoRoot {
    $current = (Get-Location).Path
    while ($current -ne [System.IO.Path]::GetPathRoot($current)) {
        if ((Test-Path (Join-Path $current '.git')) -or
            (Test-Path (Join-Path $current 'pyproject.toml')) -or
            (Test-Path (Join-Path $current 'package.json'))) {
            return $current
        }
        $current = Split-Path -Parent $current
    }
    return (Get-Location).Path
}

$RootDir = Find-RepoRoot
$DocsDir = Join-Path $RootDir 'docs'
$AdrDir = Join-Path $DocsDir 'adr'
$ArchDoc = Join-Path $DocsDir 'architecture.md'
$GroundRules = Join-Path $DocsDir 'ground-rules.md'
$SpecsDir = Join-Path $RootDir 'specs'

# Create directories
New-Item -Path $DocsDir -ItemType Directory -Force | Out-Null
New-Item -Path $AdrDir -ItemType Directory -Force | Out-Null

# Copy template if not exists
$template = Join-Path $TemplatesDir 'arch-template.md'
if (-not (Test-Path $ArchDoc -PathType Leaf)) {
    if (Test-Path $template -PathType Leaf) {
        Copy-Item -Path $template -Destination $ArchDoc -Force
    } else {
        Set-Content -Path $ArchDoc -Value "# System Architecture`n`nGenerated by architecture-design skill." -Encoding UTF8
    }
}

# Find feature specs
$featureSpecs = @()
if (Test-Path $SpecsDir -PathType Container) {
    Get-ChildItem -Path $SpecsDir -Recurse -Filter 'spec.md' | ForEach-Object {
        $rel = $_.FullName.Substring($RootDir.Length + 1) -replace '\\', '/'
        $featureSpecs += $rel
    }
}

$ProductName = Split-Path -Leaf $RootDir

# Relative paths
function Get-RelPath { param([string]$Full) return $Full.Substring($RootDir.Length + 1) -replace '\\', '/' }

$result = @{
    ARCH_DOC      = Get-RelPath $ArchDoc
    DOCS_DIR      = Get-RelPath $DocsDir
    ADR_DIR       = Get-RelPath $AdrDir
    SPECS_DIR     = if (Test-Path $SpecsDir) { Get-RelPath $SpecsDir } else { '' }
    SPEC_COUNT    = $featureSpecs.Count
    FEATURE_SPECS = $featureSpecs
    PRODUCT_NAME  = $ProductName
    GROUND_RULES  = if (Test-Path $GroundRules) { Get-RelPath $GroundRules } else { '' }
}

$result | ConvertTo-Json -Compress
