#!/usr/bin/env bash
# Set up architecture design environment and copy templates.
#
# Usage: bash scripts/setup-architect.sh
# Platforms: macOS, Linux, WSL, Git Bash
# Requirements: Bash 4.0+

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATES_DIR="$SKILL_DIR/templates"

# Find repository root
find_repo_root() {
    local current
    current="$(pwd)"
    while [[ "$current" != "/" ]]; do
        if [[ -d "$current/.git" || -f "$current/pyproject.toml" || -f "$current/package.json" ]]; then
            echo "$current"
            return
        fi
        current="$(dirname "$current")"
    done
    pwd
}

ROOT_DIR="$(find_repo_root)"
DOCS_DIR="$ROOT_DIR/docs"
ADR_DIR="$DOCS_DIR/adr"
ARCH_DOC="$DOCS_DIR/architecture.md"
GROUND_RULES="$DOCS_DIR/ground-rules.md"
SPECS_DIR="$ROOT_DIR/specs"

# Create directories
mkdir -p "$DOCS_DIR" "$ADR_DIR"

# Copy template if architecture doc doesn't exist
TEMPLATE="$TEMPLATES_DIR/arch-template.md"
if [[ ! -f "$ARCH_DOC" ]]; then
    if [[ -f "$TEMPLATE" ]]; then
        cp "$TEMPLATE" "$ARCH_DOC"
    else
        echo "# System Architecture" > "$ARCH_DOC"
        echo "" >> "$ARCH_DOC"
        echo "Generated by architecture-design skill." >> "$ARCH_DOC"
    fi
fi

# Find feature specifications
FEATURE_SPECS="[]"
SPEC_COUNT=0
if [[ -d "$SPECS_DIR" ]]; then
    specs=()
    while IFS= read -r -d '' spec; do
        rel="${spec#$ROOT_DIR/}"
        specs+=("\"$rel\"")
    done < <(find "$SPECS_DIR" -name "spec.md" -print0 2>/dev/null)
    SPEC_COUNT=${#specs[@]}
    if [[ $SPEC_COUNT -gt 0 ]]; then
        FEATURE_SPECS="[$(IFS=,; echo "${specs[*]}")]"
    fi
fi

PRODUCT_NAME="$(basename "$ROOT_DIR")"

# Compute relative paths
rel_arch="${ARCH_DOC#$ROOT_DIR/}"
rel_docs="${DOCS_DIR#$ROOT_DIR/}"
rel_adr="${ADR_DIR#$ROOT_DIR/}"
rel_specs="${SPECS_DIR#$ROOT_DIR/}"
rel_gr=""
[[ -f "$GROUND_RULES" ]] && rel_gr="${GROUND_RULES#$ROOT_DIR/}"

cat <<EOF
{"ARCH_DOC":"$rel_arch","DOCS_DIR":"$rel_docs","ADR_DIR":"$rel_adr","SPECS_DIR":"$rel_specs","SPEC_COUNT":$SPEC_COUNT,"FEATURE_SPECS":$FEATURE_SPECS,"PRODUCT_NAME":"$PRODUCT_NAME","GROUND_RULES":"$rel_gr"}
EOF
